{% set name = "pyshqg" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyshqg-{{ version }}.tar.gz
  sha256: 07c849b64cf351de5cf8b8afc946fd30741304bfc54d744aae013c3b7be981f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - numpy
    - pyshtools ==4.10.4
    - xarray
    - zarr
    - tqdm

test:
  imports:
    - pyshqg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cerea-daml/pyshqg
  summary: QG Model in spherical harmonics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aFarchi
